### ISSUE TITLE
PHP 8.1-2-3 support

### ISSUE THREAD

**Issue by eshimischi** [getwarp/warp#10]
Актуально.

**Comment by tntrex** [comment]
Привет.

В CI тесты гоняются на всех версиях поддерживаемых версиях: 7.4, 8.0, 8.1 и 8.2.

PHP 8.3 надо будет добавить, но это наверное сделаю после стабильного релиза.

**Comment by eshimischi** [comment]
В принципе нет ничего в коде, что не совместимо, имел ввиду просто поднять версию в composer.json

**Comment by tntrex** [comment]
> имел ввиду просто поднять версию в composer.json

Это не зачем. Текущее ограничение `^7.4|^8.0` указывает на поддержку всех минорных версий PHP8 и PHP7.4

Когда будет Warp4, минимально поддерживаемая версия PHP само собой повысится до актуальной

**Comment by eshimischi** [comment]
> > имел ввиду просто поднять версию в composer.json
> 
> Это не зачем. Текущее ограничение `^7.4|^8.0` указывает на поддержку всех минорных версий PHP8 и PHP7.4
> 
> Когда будет Warp4, минимально поддерживаемая версия PHP само собой повысится до актуальной

а ну если будет 4ка, то тогда да)
